[package]
name = "steering"
version = "0.1.0"
edition = "2021"
authors = ["rakeshbs <rakeshbs@gmail.com>"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nannou = "0.18"
rayon = "1.5.3"

